// GENERATED by forms-api/scripts/generate_terms.py -- do not edit by hand.
//
// Each entry is one typeset line of the agreement's static terms, placed at
// the exact coordinate the reference PDF uses: y/x in points, w the measure
// to justify within, j whether the line was justified, t its text.
export interface TermLine {
  y: number;
  x: number;
  w: number;
  j: boolean;
  t: string;
}

export interface TermsSheet {
  page: number;
  columns: TermLine[][];
}

export const TERMS_SHEETS: TermsSheet[] = [
  {
    "page": 5,
    "columns": [
      [
        {
          "y": 35.83,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "ASBESTOS / HAZARDOUS MATERIALS"
        },
        {
          "y": 46.08,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Owner represents that the property being improved does not contain"
        },
        {
          "y": 56.43,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "asbestos and / or other hazardous materials. This contract does not"
        },
        {
          "y": 66.78,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "contemplate the removal of, testing for appropriate corrective work and"
        },
        {
          "y": 77.13,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "any other additional expenses incurred by the corrective work."
        },
        {
          "y": 91.98,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "CONTRACTOR’S RIGHTS AND RESPONSIBILITIES"
        },
        {
          "y": 101.73,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "1. SUBCONTRACTORS. Contractor may subcontract all or any portion of"
        },
        {
          "y": 111.53,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "the work."
        },
        {
          "y": 121.28,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "2. Contractor shall have the right to stop work and keep the job idle if"
        },
        {
          "y": 131.08,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "payments are not made when due. Failure to make payment within five (5)"
        },
        {
          "y": 140.83,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "days of the date that payment is due will be considered a material breach of"
        },
        {
          "y": 150.63,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "this agreement. If the work shall be stopped for any reason, for a period of"
        },
        {
          "y": 160.38,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "sixty (60) days, then Contractor may, at Contractor’s option, upon five (5)"
        },
        {
          "y": 170.18,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "days written notice, demand and receive payment for all work executed and"
        },
        {
          "y": 179.93,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "material ordered or supplied and any other loss sustained including"
        },
        {
          "y": 189.73,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Contractor’s usual fee for overhead and profit based upon the contract price."
        },
        {
          "y": 199.48,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Thereafter, Contractor is relieved from any further liability. In the event of"
        },
        {
          "y": 209.28,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "work stoppage for any reason, Owner, shall provide for protection of and be"
        },
        {
          "y": 219.03,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "responsible for, any damage, warpage, racking, or loss of material on the"
        },
        {
          "y": 228.83,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "premises."
        },
        {
          "y": 238.58,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "3. Contractor, at Contractor’s option, may alter specifications only so as to"
        },
        {
          "y": 248.38,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "comply with requirements of governmental agencies having jurisdiction"
        },
        {
          "y": 258.13,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "over same. Any alterations or work undertaken to further this end shall be"
        },
        {
          "y": 267.93,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "treated as an Extra Work."
        },
        {
          "y": 282.68,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "CONTRACTOR’S RESPONSIBILITIES AND LIMITED WARRANTY"
        },
        {
          "y": 292.48,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "1. Contractor agrees to furnish the materials for the project and complete"
        },
        {
          "y": 302.23,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "the work in a professional manner. All materials furnished under this"
        },
        {
          "y": 312.03,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Agreement shall be construction grade and meet industry standards. Where"
        },
        {
          "y": 321.78,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "brand names have been specified, Contractor may select substitutes when"
        },
        {
          "y": 331.58,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "such substitutions are due to unavailability or other circumstances beyond"
        },
        {
          "y": 341.33,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Contractor’s control. All substitutions shall be consistent in quality and"
        },
        {
          "y": 351.08,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "character to the selections previously specified. THE LIABILITY OF THE"
        },
        {
          "y": 360.88,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "CONTRACTOR FOR DEFECTIVE MATERIALS OR INSTALLATION"
        },
        {
          "y": 370.63,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "IS HEREBY LIMITED TO THE REPLACEMENT OR CORRECTION OF"
        },
        {
          "y": 380.43,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "SAID DEFECTIVE MATERIAL AND / OR INSTALLATION, AND NO"
        },
        {
          "y": 390.18,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "OTHER CLAIMS, OR DEMANDS WHATSOEVER SHALL BE MADE"
        },
        {
          "y": 399.98,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "UPON OR ALLOWED AGAINST THE CONTRACTOR. THIS LIMITED"
        },
        {
          "y": 409.73,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "WARRANTY EXTENDS ONLY TO OWNER AND IS NOT"
        },
        {
          "y": 419.53,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "TRANSFERABLE. THERE IS NO IMPLIED WARRANTY OR"
        },
        {
          "y": 429.28,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "MERCHANTABILIY NOR ANY IMPLIED WARRANTY OF FITNESS"
        },
        {
          "y": 439.08,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "FOR ANY PARTICULAR PURPOSE. THERE ARE NO WARRANTIES"
        },
        {
          "y": 448.83,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "EITHER EXPRESSED OR IMPLIED WHICH EXTEND BEYOND THE"
        },
        {
          "y": 458.63,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "DESCRIPTION WITHIN THIS PARAGRAPH #1. THIS WARRANTY"
        },
        {
          "y": 468.38,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "SHALL TERMINATE ONE YEAR FROM FINAL BUILDING"
        },
        {
          "y": 478.18,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "INSPECTION OR THE DATE OF THE COMPLETION, WHICHEVER IS"
        },
        {
          "y": 487.93,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "FIRST."
        },
        {
          "y": 497.73,
          "x": 45.35,
          "w": 253.75,
          "j": true,
          "t": "NOTE THAT EQUIPMENT, ASSEMBLIES, OR UNITS PURCHASED"
        },
        {
          "y": 507.48,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "BY CONTRACTOR, INCLUDED IN THIS CONTRACT ARE SOLD"
        },
        {
          "y": 517.28,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "AND INSTALLED SUBJECT TO THE MANUFACTURER’S OR"
        },
        {
          "y": 527.03,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "PROCESSOR’S GUARANTEE OR WARRANTIES, AND NOT"
        },
        {
          "y": 536.83,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "CONTRACTOR’S. TO THE EXTENT PERMITTED BY APPLICABLE"
        },
        {
          "y": 546.58,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "LAW, ALL WARRANTIES GIVEN BY MANUFACTURERS"
        },
        {
          "y": 556.38,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "PERTAINING TO MATERALS USED BY CONTRACTOR IN"
        },
        {
          "y": 566.13,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "CONNECTION WITH THE PROJECT WILL BE PASSED THROUGH"
        },
        {
          "y": 575.93,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "AND INURE TO THE BENEFIT OF OWNER."
        },
        {
          "y": 585.68,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "2. Contractor shall pay all subcontractors, laborers and material suppliers."
        },
        {
          "y": 595.48,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Contractor shall, to the best of Contractor’s ability, keep Owner’s property"
        },
        {
          "y": 605.23,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "free of valid labor or material suppliers liens."
        },
        {
          "y": 615.03,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "3. A notice concerning workers' compensation insurance is attached to this"
        },
        {
          "y": 624.78,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "contract."
        },
        {
          "y": 634.58,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "4. A notice concerning commercial general liability insurance is attached to"
        },
        {
          "y": 644.33,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "this contract."
        },
        {
          "y": 659.08,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "ITEMS NOT RESPONSIBILITY OF CONTRACTOR"
        },
        {
          "y": 668.88,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "1. EXISTING VIOLATIONS AND CONDITIONS. Contractor shall not be"
        },
        {
          "y": 678.63,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "held responsible for any existing violations of applicable building"
        },
        {
          "y": 688.43,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "regulations or ordinances, whether cited by the appropriate authority or not."
        },
        {
          "y": 698.18,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Contractor is not responsible for any abnormal or unusual preexisting"
        },
        {
          "y": 707.98,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "conditions or any unusual or abnormal concrete footings, foundations,"
        }
      ],
      [
        {
          "y": 35.83,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "retaining walls, or piers required, or any unusual depth required for same,"
        },
        {
          "y": 45.58,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "such as, but not limited to that condition caused by poor soil, lack of"
        },
        {
          "y": 55.33,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "compaction, hillside, or other slope conditions. Correction of such violations"
        },
        {
          "y": 65.13,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "or abnormal conditions by Contractor shall be considered additional work"
        },
        {
          "y": 74.88,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "and shall be dealt with as herein provided for under “Extra Work”."
        },
        {
          "y": 84.68,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "2. DELAYS. Contractor agrees to start and diligently pursue work through"
        },
        {
          "y": 94.43,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "to completion, but shall not be responsible for delays for any of the"
        },
        {
          "y": 104.23,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "following reasons; failure of the issuance of all necessary building permits"
        },
        {
          "y": 113.98,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "within a reasonable length of time, funding of loans, disbursement of funds"
        },
        {
          "y": 123.78,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "into funding control or escrow, acts of neglect or omission of Owner or"
        },
        {
          "y": 133.53,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "Owner’s employees or Owner’s agent, acts of God, stormy or inclement"
        },
        {
          "y": 143.33,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "weather, strikes, lockouts boycotts, or other labor union activities, extra"
        },
        {
          "y": 153.08,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "work ordered by Owner, acts of public enemy, riots or civil commotion,"
        },
        {
          "y": 162.88,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "inability to secure material through regular recognized channels, imposition"
        },
        {
          "y": 172.63,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "of Government priority or allocation of materials, failure of Owner to make"
        },
        {
          "y": 182.43,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "payments when due, or delays caused by inspection or changes ordered by"
        },
        {
          "y": 192.18,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "the inspectors of authorized governmental bodies, or for acts of independent"
        },
        {
          "y": 201.98,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "contractors, or holidays, or other causes beyond Contractor’s reasonable"
        },
        {
          "y": 211.73,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "control."
        },
        {
          "y": 221.53,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "3. Contractor is not responsible for matching existing paint or texture and"
        },
        {
          "y": 231.28,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "further, there is no guarantee against hairline cracks or discolorization in"
        },
        {
          "y": 241.08,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "stucco or concrete."
        },
        {
          "y": 257.83,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "OWNER'S RESPONSIBILITIES"
        },
        {
          "y": 267.63,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "UTILITIES"
        },
        {
          "y": 277.38,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "1. The Owner is responsible for water, gas, sewer and electric utilities, from"
        },
        {
          "y": 287.18,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "the appropriate agency to the metering device, unless otherwise agreed to in"
        },
        {
          "y": 296.93,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "writing. It is the Owner’s responsibility, at Owner’s expense, to provide"
        },
        {
          "y": 306.73,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "electricity and water to the site as needed by the Contractor."
        },
        {
          "y": 316.48,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "ACCESS TO PROPERTY"
        },
        {
          "y": 326.28,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "2. Owner agrees to keep driveway clear and available for movement and"
        },
        {
          "y": 336.03,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "parking of trucks and other equipment during normal working hours. If"
        },
        {
          "y": 345.78,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "Owner denies access to any worker or material supplier during the"
        },
        {
          "y": 355.58,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "scheduled working hours, the Owner will be held in breach of the"
        },
        {
          "y": 365.33,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "Agreement and will be liable for such breach."
        },
        {
          "y": 375.13,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "FINANCING"
        },
        {
          "y": 384.88,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "3. The Owner is responsible for having sufficient funds to comply with this"
        },
        {
          "y": 394.68,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "Agreement. This is a cash transaction."
        },
        {
          "y": 404.43,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "INSURANCE"
        },
        {
          "y": 414.23,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "4. Owner will purchase insurance at Owner’s expense before any work"
        },
        {
          "y": 423.98,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "begins. Such insurance will have course of construction, fire, vandalism,"
        },
        {
          "y": 433.78,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "malicious mischief and other perils, clauses attached. The insurance must be"
        },
        {
          "y": 443.53,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "in an amount at least equal to the contract price and provide that any loss be"
        },
        {
          "y": 453.33,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "payable to the Contractor. The insurance is to cover the Owner, Contractor,"
        },
        {
          "y": 463.08,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "Subcontractor and Construction Lender in the amount of their respective"
        },
        {
          "y": 472.88,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "interests."
        },
        {
          "y": 482.63,
          "x": 324.35,
          "w": 253.35,
          "j": true,
          "t": "If the Owner does not purchase such insurance, the Contractor, as agent"
        },
        {
          "y": 492.43,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "for the Owner may purchase it and charge such cost to the Owner."
        },
        {
          "y": 502.18,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "DAMAGE OR DESTRUCTION"
        },
        {
          "y": 511.98,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "5. If the project or any portion of it is destroyed or damaged by fire, storm,"
        },
        {
          "y": 521.73,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "flood, landslide, earthquake, theft, or other disaster or accidents, any work"
        },
        {
          "y": 531.53,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "done by the Contractor to rebuild, etc., shall be paid for by Owner as an"
        },
        {
          "y": 541.28,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "Extra and dealt with as herein provided for under “Extra Work”."
        },
        {
          "y": 551.08,
          "x": 324.35,
          "w": 253.35,
          "j": true,
          "t": "In the event of any of the above occurrences, If the cost of replacement"
        },
        {
          "y": 560.83,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "work, for work already done by the Contractor, exceeds twenty (20) percent"
        },
        {
          "y": 570.63,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "of the contract price, the Owner has the option to cancel the contract but, if"
        },
        {
          "y": 580.38,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "the Owner cancels, the Contractor shall be paid for all costs incurred plus"
        },
        {
          "y": 590.18,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "Contractor’s usual fee for overhead and profit for all work performed by"
        },
        {
          "y": 599.93,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "Contractor to date of cancellation."
        },
        {
          "y": 609.73,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "OWNER’S PROPERTY"
        },
        {
          "y": 619.48,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "6. It is the Owner’s responsibility to remove or protect any personal"
        },
        {
          "y": 629.28,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "property including, but not limited to, carpets, drapes, furniture, driveways,"
        },
        {
          "y": 639.03,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "lawns, and shrubs, and Contractor will not be held responsible for damages"
        },
        {
          "y": 648.78,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "or loss of said items."
        },
        {
          "y": 658.58,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "NOTICE OF COMPLETION"
        },
        {
          "y": 668.33,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "7. Owner agrees to sign & record a Notice of Completion within five (5)"
        },
        {
          "y": 678.13,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "days after the project is substantially completed and ready for occupancy."
        },
        {
          "y": 687.88,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "Failure by the Owner to do so authorizes the Contractor to act as the"
        },
        {
          "y": 697.68,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "Owner’s agent to sign and record a Notice of Completion. This agency is"
        },
        {
          "y": 707.43,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "irrevocable and is an agency coupled with an interest. The Contractor has"
        },
        {
          "y": 717.23,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "the right to bar occupancy of the project by Owner or anyone else until"
        }
      ]
    ]
  },
  {
    "page": 6,
    "columns": [
      [
        {
          "y": 35.83,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Contractor has received all payments due under the contract and the Notice"
        },
        {
          "y": 45.58,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "of Completion is recorded. When the Owner or another authorized by the"
        },
        {
          "y": 55.33,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Owner uses and / or occupies the premises then the project is considered"
        },
        {
          "y": 65.13,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "completed. If a funding or joint control is used it is agreed that the control"
        },
        {
          "y": 74.88,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "shall act as the Owner’s agent and sign and record a Notice of Completion."
        },
        {
          "y": 84.68,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "BOUNDRY LINES"
        },
        {
          "y": 94.43,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "8. The Owner represents ownership of the property where construction is to"
        },
        {
          "y": 104.23,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "occur. It is the Owner’s duty to point out boundary lines of the property and"
        },
        {
          "y": 113.98,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Owner is responsible for the accuracy of such lines and how they are"
        },
        {
          "y": 123.78,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "represented on drawings. If required, the Owner will pay for a survey to"
        },
        {
          "y": 133.53,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "chart boundary lines."
        },
        {
          "y": 143.33,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "EASEMENTS, ETC."
        },
        {
          "y": 153.08,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "9. Prior to construction the Owner is to give the Contractor a copy of any"
        },
        {
          "y": 162.88,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "easements, restrictions or rights of way relating to the property. If Owner"
        },
        {
          "y": 172.63,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "does not do so, Contractor will assume that none exist."
        },
        {
          "y": 182.43,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "ENGINEERING AND GEOLOGY"
        },
        {
          "y": 192.18,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "10.Unless specifically agreed upon in writing between Owner and"
        },
        {
          "y": 201.98,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Contractor, and made a part of this Agreement under “Description of"
        },
        {
          "y": 211.73,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Materials”, “Specifications” or “Plans”, this agreement does not include any"
        },
        {
          "y": 221.53,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "engineering or geology surveys, drawings, studies, reports or calculations as"
        },
        {
          "y": 231.28,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "may be required by a public body or building authority as a condition for"
        },
        {
          "y": 241.08,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "issuance of building permit or as a condition to securing final building"
        },
        {
          "y": 250.83,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "inspection. The cost of any such required professional services shall be paid"
        },
        {
          "y": 260.63,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "by Owner."
        },
        {
          "y": 270.38,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "OTHER"
        },
        {
          "y": 280.18,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "DRAWINGS AND SPECIFICATIONS"
        },
        {
          "y": 289.93,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "1. The project will be constructed according to drawings and specifications"
        },
        {
          "y": 299.73,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "that have been examined by Owner and that have been or may be signed by"
        },
        {
          "y": 309.48,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "the parties to this contract. Unless specifically provided in the drawing or"
        },
        {
          "y": 319.28,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "specifications, Contractor will obtain and pay for all required building"
        },
        {
          "y": 329.03,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "permits. Owner will pay any assessments and charges required by public"
        },
        {
          "y": 338.78,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "bodies and utilities for financing or repaying the cost of sewers, storm drains,"
        },
        {
          "y": 348.58,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "water service, or other utilities including sewer and storm drain"
        },
        {
          "y": 358.33,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "reimbursement charges, use fees, revolving fund charges, hookup charges"
        },
        {
          "y": 368.13,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "and the like."
        },
        {
          "y": 377.88,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "ITEMS EXCLUDED"
        },
        {
          "y": 387.68,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "2. Unless specifically agreed upon in writing between Owner and"
        },
        {
          "y": 397.43,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "Contractor and made part of this Agreement, under “Description of Work”,"
        },
        {
          "y": 407.23,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "“Description of Material”, “Specifications”, or “Plans”, this contract does"
        },
        {
          "y": 416.98,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "not include:"
        },
        {
          "y": 426.78,
          "x": 45.35,
          "w": 253.75,
          "j": true,
          "t": "a. Plumbing, gas, waste and water lines outside foundations of"
        },
        {
          "y": 436.53,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "existing buildings or any required relocation or replacement of any such"
        },
        {
          "y": 446.33,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "existing lines that may be discovered within the boundaries of any new"
        },
        {
          "y": 456.08,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "ground floor addition"
        },
        {
          "y": 465.88,
          "x": 45.35,
          "w": 253.75,
          "j": true,
          "t": "b. Electrical service, other than addition of circuit breakers or fuse"
        },
        {
          "y": 475.63,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "blocks to distribute electric current to new outlets;"
        },
        {
          "y": 485.43,
          "x": 45.35,
          "w": 253.75,
          "j": true,
          "t": "c. Any work which may be required regarding cesspools or septic"
        },
        {
          "y": 495.18,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "tanks."
        },
        {
          "y": 504.98,
          "x": 45.35,
          "w": 253.75,
          "j": true,
          "t": "d. Rerouting, relocating or replacing vents, pipes, ducts or conduits"
        },
        {
          "y": 514.73,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "not shown or those encountered during construction or changes required to"
        },
        {
          "y": 524.53,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "existing wiring, vents, pipes, ducts or conduits in areas undisturbed by"
        },
        {
          "y": 534.28,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "construction. Unless specified elsewhere, existing wiring and electrical"
        },
        {
          "y": 544.08,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "systems are represented by the Owner as adequate to carry load for existing"
        },
        {
          "y": 553.83,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "structure and work to be performed herein;"
        },
        {
          "y": 563.63,
          "x": 45.35,
          "w": 253.75,
          "j": true,
          "t": "e. Any additional work required for excavation or foundations due"
        },
        {
          "y": 573.38,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "to inadequate bearing capacity or rock or any other material not removable"
        },
        {
          "y": 583.18,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "by ordinary hand tools"
        },
        {
          "y": 592.93,
          "x": 45.35,
          "w": 253.75,
          "j": false,
          "t": "f. Any work to correct damage caused by termites or dry rot;"
        },
        {
          "y": 602.73,
          "x": 45.35,
          "w": 253.75,
          "j": true,
          "t": "g. Changes or alterations from the specifications which may be"
        },
        {
          "y": 612.48,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "required by any public body, utility or inspector."
        },
        {
          "y": 622.28,
          "x": 45.35,
          "w": 253.75,
          "j": true,
          "t": "h. Painting, preparation, filing, finishing, grading, retaining wails,"
        },
        {
          "y": 632.03,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "new or relocating gutters and downspouts, screen doors, weather stripping,"
        },
        {
          "y": 641.78,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "staining, seeding, landscaping, or decorating. Any work necessary to correct,"
        },
        {
          "y": 651.58,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "change, alter or add the above items will be considered additional work and"
        },
        {
          "y": 661.33,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "shall be dealt with as herein provided for under “Extra Work”."
        },
        {
          "y": 671.13,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "MEASUREMENTS"
        },
        {
          "y": 680.88,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "3. Measurements, sizes and shapes in plans and specifications are"
        },
        {
          "y": 690.68,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "approximate and subject to field verification. Unless otherwise specified, all"
        },
        {
          "y": 700.43,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "dimensions are exterior dimensions. In the event of a conflict between the"
        }
      ],
      [
        {
          "y": 35.83,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "plans, specifications, etc., and the Agreement, this Agreement is controlling."
        },
        {
          "y": 45.58,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "Contractor is not responsible for any existing illegal conditions."
        },
        {
          "y": 55.33,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "MATERIAL REMOVED AND DEBRIS"
        },
        {
          "y": 65.13,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "4. Unless specifically designated by Owner in writing, prior to"
        },
        {
          "y": 74.88,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "commencement of construction, Contractor may dispose of all material"
        },
        {
          "y": 84.68,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "removed from structures in course of alteration. Also the Contractor is to"
        },
        {
          "y": 94.43,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "remove construction debris at the end of the project and leave premises in a"
        },
        {
          "y": 104.23,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "neat broom-clean condition."
        },
        {
          "y": 113.98,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "FLOOR COVERING"
        },
        {
          "y": 123.78,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "5. Unless specifically agreed upon in writing, floor covering is not covered"
        },
        {
          "y": 133.53,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "under this Agreement."
        },
        {
          "y": 143.33,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "ADDITIONAL REQUIREMENTS FOR COMPLETION"
        },
        {
          "y": 153.08,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "6. Contractor shall promptly notify Owner of any additional requirements"
        },
        {
          "y": 162.88,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "necessary to facilitate the project’s completion. Any subsequent amendment,"
        },
        {
          "y": 172.63,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "modification or agreement, which operates to alter this contract, and which"
        },
        {
          "y": 182.43,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "is signed or initialed by Contractor and Owner, shall be deemed a part of"
        },
        {
          "y": 192.18,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "this contract and shall be controlling in case of conflict, to the extent that it"
        },
        {
          "y": 201.98,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "alters this contract."
        },
        {
          "y": 211.73,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "NOTE ABOUT EXTRA WORK AND CHANGE ORDERS"
        },
        {
          "y": 221.53,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "7. Extra Work and Change Orders become part of the contract once the"
        },
        {
          "y": 231.28,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "order is prepared in writing and signed by the parties prior to the"
        },
        {
          "y": 241.08,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "commencement of any work covered by the new change order. The order"
        },
        {
          "y": 250.83,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "must describe the scope of the extra work or change, the cost to be added or"
        },
        {
          "y": 260.63,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "subtracted from the contract, and the effect the order will have on the"
        },
        {
          "y": 270.38,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "schedule of progress payments. Failure to have written authorization shall"
        },
        {
          "y": 280.18,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "not be deemed fatal to the collection of the extra work."
        },
        {
          "y": 289.93,
          "x": 324.35,
          "w": 253.35,
          "j": true,
          "t": "For any extra work performed. Contractor shall be compensated in an"
        },
        {
          "y": 299.73,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "amount to be determined before the extra work is performed and such"
        },
        {
          "y": 309.48,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "amount including Contractor’s usual fee for overhead and profit shall be"
        },
        {
          "y": 319.28,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "made as the extra work progresses, concurrently with payments, made under"
        },
        {
          "y": 329.03,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "the payments scheduled."
        },
        {
          "y": 338.78,
          "x": 324.35,
          "w": 253.35,
          "j": true,
          "t": "Any change-order forms for changes or extra work shall be incorporated"
        },
        {
          "y": 348.58,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "in, and become part of the contract."
        },
        {
          "y": 363.33,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "STANDARDS FOR SPECIFICATIONS"
        },
        {
          "y": 373.13,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "8. If all or any part of the following is included in this Agreement under"
        },
        {
          "y": 382.88,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "Specifications, the following will apply: All cabinets to be paint grade, or if"
        },
        {
          "y": 392.68,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "same is noted to be other than paint grade, to be of veneer construction. All"
        },
        {
          "y": 402.43,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "cabinet doors to be lipped construction. All inside portions such as shelves,"
        },
        {
          "y": 412.23,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "bulkheads, and partitions may be of other species than exposed portions, but"
        },
        {
          "y": 421.98,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "not limited to solid stock plywood, or particle board with fixed shelve"
        },
        {
          "y": 431.78,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "without backs. All plumbing fixtures to be white in color and selected by"
        },
        {
          "y": 441.53,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "Contractor. All appliances and fixtures to be Builders models. Medicine"
        },
        {
          "y": 451.33,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "cabinets to be single, recessed, and metal. Tile, if ceramic, to be domestic,"
        },
        {
          "y": 460.53,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "non-decorator, 4¼” x 4¼”. All fireplaces to be prefab with a metal flue."
        },
        {
          "y": 470.88,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "All extra materials remain the property of the Contractor. If any of the"
        },
        {
          "y": 480.63,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "materials used vary from the above, such variation must be agreed upon"
        },
        {
          "y": 490.43,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "between Contractor and Owner, in writing and listed in this Agreement"
        },
        {
          "y": 500.18,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "under “Specifications”, “Description of Materials” or attached to this"
        },
        {
          "y": 509.98,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "Agreement and initialed by Owner and Contractor."
        },
        {
          "y": 519.73,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "CORRECTIVE WORK"
        },
        {
          "y": 529.53,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "9. If minor corrective or repair work remains to be finished after the project"
        },
        {
          "y": 539.28,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "is ready for occupancy, Contractor shall perform work expeditiously and"
        },
        {
          "y": 549.08,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "Owner shall not withhold any payment pending completion of such work. If"
        },
        {
          "y": 558.83,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "major corrective or repair work remains to be finished after the building is"
        },
        {
          "y": 568.63,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "ready for occupancy, and the cost exceeds one (1) percent of the gross"
        },
        {
          "y": 578.38,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "contract price, the Owner may withhold payment sufficient to pay for"
        },
        {
          "y": 588.18,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "completion of the work, pending completion of the work, but may not"
        },
        {
          "y": 597.93,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "withhold an amount which is greater."
        },
        {
          "y": 612.73,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "GENERAL"
        },
        {
          "y": 622.48,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "10.This contract, including incorporated documents, constitutes the entire"
        },
        {
          "y": 632.28,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "agreement of the parties. No other oral or written agreements between"
        },
        {
          "y": 642.03,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "Contractor and Owner, regarding construction to be performed exist."
        },
        {
          "y": 651.78,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "11.This Agreement shall be construed in accordance with, and governed by,"
        },
        {
          "y": 661.58,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "the laws of the State of California."
        },
        {
          "y": 671.33,
          "x": 315.0,
          "w": 262.7,
          "j": false,
          "t": "NOTICE"
        },
        {
          "y": 681.13,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "12.Any notice required or permitted under this contract may be given by"
        },
        {
          "y": 690.88,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "ordinary mail sent to the address of either the Owner or Contractor as listed"
        },
        {
          "y": 700.68,
          "x": 315.0,
          "w": 262.7,
          "j": true,
          "t": "in this contract, but the address may be changed by written notice from one"
        }
      ]
    ]
  },
  {
    "page": 7,
    "columns": [
      [
        {
          "y": 35.83,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "party to the other. Notice is considered received five (5) days after"
        },
        {
          "y": 45.58,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "deposited in the mail, postage paid."
        },
        {
          "y": 55.33,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "ATTORNEY FEES"
        },
        {
          "y": 65.13,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "In the event legal action or arbitration is instituted for the enforcement of"
        },
        {
          "y": 74.88,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "any term or condition of this Agreement, the prevailing party shall be"
        },
        {
          "y": 84.68,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "entitled to an award of reasonable attorney fees in said action or arbitration,"
        },
        {
          "y": 94.43,
          "x": 36.0,
          "w": 263.1,
          "j": true,
          "t": "in addition to costs and reasonable expenses incurred in the prosecution or"
        },
        {
          "y": 104.23,
          "x": 36.0,
          "w": 263.1,
          "j": false,
          "t": "defense of said action or arbitration."
        }
      ],
      []
    ]
  }
];
