"""GENERATED by server/scripts/generate_docx_order.py -- do not edit.

Child element order for the containers the Word builder writes into.
Word refuses to open a document that gets these wrong, so `kit._child`
inserts by this table rather than appending.
"""

ORDER: dict[str, tuple[str, ...]] = {
    "w:pPr": (
        "pStyle", "keepNext", "keepLines", "pageBreakBefore", "framePr",
        "widowControl", "numPr", "suppressLineNumbers", "pBdr", "shd", "tabs",
        "suppressAutoHyphens", "kinsoku", "wordWrap", "overflowPunct",
        "topLinePunct", "autoSpaceDE", "autoSpaceDN", "bidi", "adjustRightInd",
        "snapToGrid", "spacing", "ind", "contextualSpacing", "mirrorIndents",
        "suppressOverlap", "jc", "textDirection", "textAlignment",
        "textboxTightWrap", "outlineLvl", "divId", "cnfStyle", "rPr", "sectPr",
        "pPrChange",
    ),
    "w:rPr": (
        "rStyle", "rFonts", "b", "bCs", "i", "iCs", "caps", "smallCaps",
        "strike", "dstrike", "outline", "shadow", "emboss", "imprint",
        "noProof", "snapToGrid", "vanish", "webHidden", "color", "spacing",
        "w", "kern", "position", "sz", "szCs", "highlight", "u", "effect",
        "bdr", "shd", "fitText", "vertAlign", "rtl", "cs", "em", "lang",
        "eastAsianLayout", "specVanish", "oMath", "rPrChange",
    ),
    "w:tblPr": (
        "tblStyle", "tblpPr", "tblOverlap", "bidiVisual",
        "tblStyleRowBandSize", "tblStyleColBandSize", "tblW", "jc",
        "tblCellSpacing", "tblInd", "tblBorders", "shd", "tblLayout",
        "tblCellMar", "tblLook", "tblCaption", "tblDescription", "tblPrChange",
    ),
    "w:tcPr": (
        "cnfStyle", "tcW", "gridSpan", "hMerge", "vMerge", "tcBorders", "shd",
        "noWrap", "tcMar", "textDirection", "tcFitText", "vAlign", "hideMark",
        "headers", "cellIns", "cellDel", "cellMerge", "tcPrChange",
    ),
    "w:trPr": (
        "cnfStyle", "divId", "gridBefore", "gridAfter", "wBefore", "wAfter",
        "cantSplit", "trHeight", "tblHeader", "tblCellSpacing", "jc", "hidden",
        "ins", "del", "trPrChange",
    ),
    "w:tr": (
        "tblPrEx", "trPr", "tc", "customXml", "sdt", "proofErr", "permStart",
        "permEnd", "bookmarkStart", "bookmarkEnd", "moveFromRangeStart",
        "moveFromRangeEnd", "moveToRangeStart", "moveToRangeEnd",
        "commentRangeStart", "commentRangeEnd", "customXmlInsRangeStart",
        "customXmlInsRangeEnd", "customXmlDelRangeStart",
        "customXmlDelRangeEnd", "customXmlMoveFromRangeStart",
        "customXmlMoveFromRangeEnd", "customXmlMoveToRangeStart",
        "customXmlMoveToRangeEnd", "ins", "del", "moveFrom", "moveTo",
    ),
    "w:sectPr": (
        "headerReference", "footerReference", "footnotePr", "endnotePr",
        "type", "pgSz", "pgMar", "paperSrc", "pgBorders", "lnNumType",
        "pgNumType", "cols", "formProt", "vAlign", "noEndnote", "titlePg",
        "textDirection", "bidi", "rtlGutter", "docGrid", "printerSettings",
        "sectPrChange",
    ),
    "w:sdtPr": (
        "rPr", "alias", "tag", "id", "lock", "placeholder", "temporary",
        "showingPlcHdr", "dataBinding", "label", "tabIndex", "equation",
        "comboBox", "date", "docPartObj", "docPartList", "dropDownList",
        "picture", "richText", "text", "citation", "group", "bibliography",
    ),
    "w:pBdr": (
        "top", "left", "bottom", "right", "between", "bar",
    ),
    "w:tblBorders": (
        "top", "start", "left", "bottom", "end", "right", "insideH", "insideV",
    ),
    "w:tcBorders": (
        "top", "start", "left", "bottom", "end", "right", "insideH", "insideV",
        "tl2br", "tr2bl",
    ),
    "w:tblCellMar": (
        "top", "start", "left", "bottom", "end", "right",
    ),
    "w:tcMar": (
        "top", "start", "left", "bottom", "end", "right",
    ),
}
