"""Generate the agreement's static terms from the reference PDF.

Pages 5-7 are fixed legal boilerplate. Rather than re-flow them in the browser
-- where the system Times is fractionally wider than the font Word embedded,
which costs three lines per column -- each line is emitted at the exact
coordinate the original uses. Run this only if the reference PDF changes.

Two files are written from the one extraction so the wording cannot drift:
`app/src/forms/termsLines.ts` for the browser, and `server/app/terms.json`
for the Word export, which reflows the lines back into paragraphs.
"""

import json
from pathlib import Path

import pymupdf

ROOT = Path(__file__).resolve().parent.parent
REFERENCE = ROOT.parent / "references" / "3360_Ramona_Palo_Alto_sample_4.pdf"
TARGET = ROOT.parent / "app" / "src" / "forms" / "termsLines.ts"
TARGET_JSON = ROOT / "app" / "terms.json"

COLUMNS = [(24.0, 306.0, 36.0, 299.1), (306.0, 588.0, 315.0, 577.7)]
PAGES = [4, 5, 6]  # zero-based: printed pages 5, 6, 7


def join_spans(spans: list[dict]) -> str:
    """Rejoin spans, restoring the spaces justification turned into gaps."""
    out = ""
    prev_right = None
    for span in sorted(spans, key=lambda s: s["bbox"][0]):
        text = span["text"]
        if not text:
            continue
        if (
            prev_right is not None
            and span["bbox"][0] - prev_right > 0.5
            and not out.endswith(" ")
            and not text.startswith(" ")
        ):
            out += " "
        out += text
        prev_right = span["bbox"][2]
    return out.rstrip()


def collect_lines(page, clip: pymupdf.Rect) -> list[list[dict]]:
    """Group spans into visual lines.

    Justification can spread a single line's words far enough apart that the
    extractor reports them as separate lines, so regroup on the baseline.
    """
    rows: dict[int, list[dict]] = {}
    for block in page.get_text("dict", clip=clip)["blocks"]:
        if block["type"] != 0:
            continue
        for line in block["lines"]:
            for span in line["spans"]:
                if not span["text"].strip():
                    continue
                rows.setdefault(round(span["bbox"][1] * 2), []).append(span)
    return [rows[key] for key in sorted(rows)]


def main() -> None:
    doc = pymupdf.open(REFERENCE)
    pages = []

    for index in PAGES:
        page = doc[index]
        columns = []
        for x0, x1, col_left, col_right in COLUMNS:
            lines = []
            for spans in collect_lines(page, pymupdf.Rect(x0, 30, x1, 735)):
                text = join_spans(spans)
                if not text.strip():
                    continue
                left = round(min(s["bbox"][0] for s in spans), 2)
                right = max(s["bbox"][2] for s in spans)
                lines.append(
                    {
                        "y": round(min(s["bbox"][1] for s in spans), 2),
                        "x": left,
                        "w": round(col_right - left, 2),
                        # A line that reaches the margin was justified; a short
                        # one ends its paragraph and must not be.
                        "j": right > col_right - 3.0,
                        "t": text,
                    }
                )
            columns.append(lines)
        pages.append({"page": index + 1, "columns": columns})
        print(f"page {index + 1}: {[len(c) for c in columns]} lines per column")

    body = json.dumps(pages, ensure_ascii=False, indent=2)
    TARGET.write_text(
        "// GENERATED by server/scripts/generate_terms.py -- do not edit by hand.\n"
        "//\n"
        "// Each entry is one typeset line of the agreement's static terms, placed at\n"
        "// the exact coordinate the reference PDF uses: y/x in points, w the measure\n"
        "// to justify within, j whether the line was justified, t its text.\n"
        "export interface TermLine {\n"
        "  y: number;\n"
        "  x: number;\n"
        "  w: number;\n"
        "  j: boolean;\n"
        "  t: string;\n"
        "}\n\n"
        "export interface TermsSheet {\n"
        "  page: number;\n"
        "  columns: TermLine[][];\n"
        "}\n\n"
        f"export const TERMS_SHEETS: TermsSheet[] = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {TARGET}")

    TARGET_JSON.write_text(body + "\n", encoding="utf-8")
    print(f"wrote {TARGET_JSON}")


if __name__ == "__main__":
    main()
