"""Generate `app/word/order.py` from the WordprocessingML schema.

Word rejects a document whose property elements are in the wrong order --
`w:pBdr` has to precede `w:spacing` inside `w:pPr`, and so on for every
container. python-docx knows these sequences but does not expose them, so
they are read straight out of `schemas/wml.xsd` instead of being retyped.

Run this if the set of containers the builder touches changes.
"""

from pathlib import Path

from lxml import etree

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "schemas" / "wml.xsd"
TARGET = ROOT / "app" / "word" / "order.py"

XSD = "{http://www.w3.org/2001/XMLSchema}"

#: The containers the Word builder inserts children into, and the schema type
#: describing each one.
CONTAINERS = {
    "w:pPr": "CT_PPr",
    "w:rPr": "CT_RPr",
    "w:tblPr": "CT_TblPr",
    "w:tcPr": "CT_TcPr",
    "w:trPr": "CT_TrPr",
    "w:tr": "CT_Row",
    "w:sectPr": "CT_SectPr",
    "w:sdtPr": "CT_SdtPr",
    "w:pBdr": "CT_PBdr",
    "w:tblBorders": "CT_TblBorders",
    "w:tcBorders": "CT_TcBorders",
    "w:tblCellMar": "CT_TblCellMar",
    "w:tcMar": "CT_TcMar",
}


class Schema:
    """Just enough of XSD to read child order out of a complex type."""

    def __init__(self, tree: etree._ElementTree) -> None:
        root = tree.getroot()
        self.types = {
            node.get("name"): node
            for node in root.findall(f"{XSD}complexType")
            if node.get("name")
        }
        self.groups = {
            node.get("name"): node
            for node in root.findall(f"{XSD}group")
            if node.get("name")
        }

    def sequence(self, name: str) -> list[str]:
        names: list[str] = []
        self._walk(self.types[name], names, set())
        return names

    def _walk(self, node, names: list[str], seen: set[str]) -> None:
        """Collect element names in document order, following the indirection.

        Particles nest: a type extends a base, a sequence holds a choice, and
        most of WordprocessingML's real content sits behind `xsd:group`
        references that have to be spliced in where they appear.
        """
        for child in node:
            tag = etree.QName(child).localname

            if tag == "extension":
                base = (child.get("base") or "").split(":")[-1]
                if base in self.types and base not in seen:
                    self._walk(self.types[base], names, seen | {base})
                self._walk(child, names, seen)

            elif tag == "group" and child.get("ref"):
                reference = child.get("ref").split(":")[-1]
                if reference in self.groups and reference not in seen:
                    self._walk(self.groups[reference], names, seen | {reference})

            elif tag == "element":
                element = child.get("name")
                if element and element not in names:
                    names.append(element)

            elif tag in ("complexContent", "simpleContent", "sequence", "choice",
                         "all", "group"):
                self._walk(child, names, seen)


def main() -> None:
    schema = Schema(etree.parse(SCHEMA))

    missing = [name for name in CONTAINERS.values() if name not in schema.types]
    if missing:
        raise SystemExit(f"not in the schema: {', '.join(missing)}")

    lines = [
        '"""GENERATED by server/scripts/generate_docx_order.py -- do not edit.',
        "",
        "Child element order for the containers the Word builder writes into.",
        "Word refuses to open a document that gets these wrong, so `kit._child`",
        "inserts by this table rather than appending.",
        '"""',
        "",
        "ORDER: dict[str, tuple[str, ...]] = {",
    ]

    for tag, type_name in CONTAINERS.items():
        children = schema.sequence(type_name)
        lines.append(f'    "{tag}": (')
        row = "       "
        for child in children:
            addition = f' "{child}",'
            if len(row) + len(addition) > 79:
                lines.append(row)
                row = "       "
            row += addition
        lines.append(row)
        lines.append("    ),")

    lines.append("}")
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {TARGET}")
    for tag, type_name in CONTAINERS.items():
        print(f"  {tag:16} {len(schema.sequence(type_name))} children")


if __name__ == "__main__":
    main()
